import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  container: {
    position: "relative",
    width: "100vw",
    height: "100vh",
    overflow: "hidden",
    background: "#0a0a0f",
    fontFamily: "'Courier New', monospace",
  },
  canvas: {
    width: "100%",
    height: "100%",
  },

  // HUD
  hud: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    display: "flex",
    justifyContent: "center",
    padding: "16px",
    pointerEvents: "none",
  },
  hudInner: {
    background: "rgba(10, 10, 15, 0.85)",
    border: "1px solid rgba(155, 89, 182, 0.4)",
    borderRadius: "2px",
    padding: "12px 24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    backdropFilter: "blur(8px)",
    boxShadow: "0 0 20px rgba(155, 89, 182, 0.15)",
  },
  hudLabel: {
    color: "rgba(155, 89, 182, 0.8)",
    fontSize: "11px",
    letterSpacing: "3px",
    textTransform: "uppercase",
  },
  hudText: {
    color: "#e8e8e8",
    fontSize: "15px",
    letterSpacing: "1px",
  },

  // Interaction hint
  interactionHint: {
    position: "absolute",
    bottom: "80px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "10px 20px",
    background: "rgba(10, 10, 15, 0.9)",
    border: "1px solid rgba(233, 69, 96, 0.5)",
    borderRadius: "2px",
    animation: "pulse 2s ease-in-out infinite",
  },
  hintKey: {
    background: "rgba(233, 69, 96, 0.2)",
    color: "#e94560",
    padding: "4px 10px",
    borderRadius: "2px",
    fontSize: "12px",
    fontWeight: "bold",
    letterSpacing: "2px",
    border: "1px solid rgba(233, 69, 96, 0.4)",
  },
  hintText: {
    color: "#ccc",
    fontSize: "13px",
    letterSpacing: "1px",
  },

  // Controls hint
  controlsHint: {
    position: "absolute",
    bottom: "20px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 10,
    padding: "8px 16px",
    pointerEvents: "none",
  },
  controlsText: {
    color: "rgba(200, 200, 200, 0.3)",
    fontSize: "12px",
    letterSpacing: "2px",
  },

  // Modal
  modalOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 100,
    background: "rgba(5, 5, 10, 0.85)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backdropFilter: "blur(4px)",
  },
  modalContent: {
    background: "#0f0f1a",
    border: "1px solid rgba(155, 89, 182, 0.3)",
    borderRadius: "2px",
    width: "90%",
    maxWidth: "480px",
    maxHeight: "70vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 0 40px rgba(155, 89, 182, 0.1)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px 24px 16px",
    borderBottom: "1px solid rgba(155, 89, 182, 0.15)",
  },
  modalTitle: {
    margin: 0,
    color: "#c4a3d4",
    fontSize: "16px",
    fontWeight: "normal",
    letterSpacing: "3px",
    fontFamily: "'Courier New', monospace",
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "#666",
    fontSize: "18px",
    cursor: "pointer",
    padding: "4px 8px",
  },

  // Input
  inputRow: {
    display: "flex",
    gap: "8px",
    padding: "16px 24px",
  },
  input: {
    flex: 1,
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(155, 89, 182, 0.2)",
    borderRadius: "2px",
    padding: "10px 14px",
    color: "#e8e8e8",
    fontSize: "14px",
    fontFamily: "'Courier New', monospace",
    outline: "none",
  },
  addBtn: {
    background: "rgba(233, 69, 96, 0.2)",
    border: "1px solid rgba(233, 69, 96, 0.4)",
    borderRadius: "2px",
    color: "#e94560",
    padding: "10px 18px",
    cursor: "pointer",
    fontSize: "13px",
    fontFamily: "'Courier New', monospace",
    letterSpacing: "2px",
    transition: "all 0.2s",
  },

  // Goal list
  goalList: {
    flex: 1,
    overflowY: "auto",
    padding: "8px 24px 20px",
  },
  emptyText: {
    color: "#555",
    textAlign: "center",
    fontSize: "13px",
    padding: "24px 0",
    letterSpacing: "1px",
  },
  goalItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 14px",
    marginBottom: "6px",
    background: "rgba(255, 255, 255, 0.02)",
    border: "1px solid rgba(155, 89, 182, 0.1)",
    borderRadius: "2px",
  },
  goalTextWrap: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  goalText: {
    color: "#d4d4d4",
    fontSize: "14px",
  },
  goalDate: {
    color: "#555",
    fontSize: "11px",
  },
  goalActions: {
    display: "flex",
    gap: "4px",
    marginLeft: "12px",
  },
  editBtn: {
    background: "none",
    border: "1px solid rgba(155, 89, 182, 0.2)",
    borderRadius: "2px",
    color: "#9b59b6",
    cursor: "pointer",
    padding: "4px 8px",
    fontSize: "14px",
  },
  deleteBtn: {
    background: "none",
    border: "1px solid rgba(233, 69, 96, 0.2)",
    borderRadius: "2px",
    color: "#e94560",
    cursor: "pointer",
    padding: "4px 8px",
    fontSize: "13px",
  },

  // Edit mode
  editRow: {
    display: "flex",
    gap: "6px",
    width: "100%",
    alignItems: "center",
  },
  editInput: {
    flex: 1,
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(155, 89, 182, 0.3)",
    borderRadius: "2px",
    padding: "8px 12px",
    color: "#e8e8e8",
    fontSize: "14px",
    fontFamily: "'Courier New', monospace",
    outline: "none",
  },
  saveBtn: {
    background: "rgba(46, 204, 113, 0.15)",
    border: "1px solid rgba(46, 204, 113, 0.3)",
    borderRadius: "2px",
    color: "#2ecc71",
    cursor: "pointer",
    padding: "6px 10px",
    fontSize: "14px",
  },
  cancelBtn: {
    background: "none",
    border: "1px solid rgba(150, 150, 150, 0.2)",
    borderRadius: "2px",
    color: "#888",
    cursor: "pointer",
    padding: "6px 10px",
    fontSize: "13px",
  },
};
